version: 2.1

app-container: &app-container circleci/ruby:2.7

jobs:
  build:
    docker:
      - image: *app-container
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker:
      - image: *app-container
    steps:
      - checkout
      - ruby/install-deps
  test:
    docker:
      - image: *app-container
      - environment:
          POSTGRES_DB: snpr
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: snpr
        image: 'circleci/postgres:9.6-alpine'
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: snpr
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
orbs:
  ruby: circleci/ruby@1.4
workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
